badshop_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

index/urls.py
from django.urls import path

from blog.views import blog, blogPage
from index.views import index, catalog, filter, catalog_page, item, brends, pay, sail, salePage, about, partners, \
    contacts, cabinet, cart, my_data, myadress, \
    delete_address, edit_myaddress, favorite, CustomUserPasswordChangeView, toggle_favorites, toggle_cart, \
    get_cart_count, get_favorite_count, update_cart_quantity, order
from users.views import AppLoginView, AppLogoutView, AppRegistration

urlpatterns = [

    # ГЛАВНАЯ СТРАНИЦА
    path('', index, name="index"),

    # КАТАЛОГ
    path('catalog/', catalog, name="catalog"),
    path('catalog/category/item/<item_id>/', item, name="item"),
    path('catalog/category/<category_id>/', catalog_page, name="catalog_page"),
    path('catalog/filter/', filter, name="filter_no_category"),
    path('catalog/filter/<category_id>/', filter, name="filter"),

    path('brends/', brends, name="brends"),
    path('pay/', pay, name="pay"),
    path('sale/', sail, name="sail"),
    path('sale/<sale_id>/', salePage, name="salePage"),

    # АУТЕНТИФИКАЦИЯ
    path('login/', AppLoginView.as_view(), name="login"),
    path('logout/', AppLogoutView.as_view(), name="logout"),
    path('registration/', AppRegistration.as_view(), name="registration"),

    # БЛОГ
    path('blog/', blog, name="blog"),
    path('blog/<post_id>/', blogPage, name="blogPage"),

    # ОСТАЛЬНЫЕ СТРАНИЦА
    path('about/', about, name="about"),
    path('partners/', partners, name="partners"),
    path('contacts/', contacts, name="contacts"),

    # ЛИЧНЫЙ КАБИНЕТ
    path('cabinet/', cabinet, name="cabinet"),
    path('cabinet/my_data/', my_data, name="my_data"),
    path('cabinet/reset_password/', CustomUserPasswordChangeView.as_view(), name="reset_password"),
    path('cabinet/my_adress/', myadress, name="myadress"),
    path('cabinet/my_adress/delete_address/<int:address_id>/', delete_address, name='delete_address'),
    path('cabinet/my_adress/edit_myaddress/<int:address_id>/', edit_myaddress, name='edit_myaddress'),
    path('cabinet/favorite/', favorite, name='favorite'),

    # КОРЗИНА
    path('cart/', cart, name="cart"),

    # РАБОТА С КАРЗИНОЙ И ИЗБРАННЫМИ
    path('get_cart_count/', get_cart_count, name="get_cart_count"),
    path('get_favorite_count/', get_favorite_count, name="get_favorite_count"),
    path('toggle_cart/<int:item_id>/', toggle_cart, name='toggle_cart'),
    path('toggle_favorites/<int:item_id>/', toggle_favorites, name='toggle_favorites'),
    path('update_quantity/<int:item_id>/<int:new_quantity>/', update_cart_quantity, name='update_quantity'),
    path('order/', order, name="order")
]

orders/models.py
from django.contrib.sessions.models import Session
from django.db import models

from balance.models import PromoCode
from items.models import CartItem
from users.models import CustomUser, Address


# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=True, null=True)
    items = models.ManyToManyField(CartItem, verbose_name='Корзина')
    total_price = models.IntegerField(verbose_name='Сумма заказа', blank=True, null=True)  # Общая сумма заказа
    date_created = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=240, blank=True, null=True, verbose_name='Комментарий к заказу')
    delivery_address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Адрес доставки')

    STATUS_CHOICES = (
        ('OP', 'Оплачен'),
        ('DL', 'Доставлен'),
        ('NP', 'Не оплачен'),
        ('DD', 'Выполняется доставка'),
    )

    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='NP', verbose_name='Статус заказа', blank=True, null=True)


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f"{self.user.email}, {self.status}"


class OrderStatus(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Статусы заказов'
        verbose_name_plural = 'Статусы заказов'


class Payment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    payment_amount = models.IntegerField()
    payment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Платеж'
        verbose_name_plural = 'Платежи'


class AppliedPromoCode(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    session = models.ForeignKey(Session, on_delete=models.SET_NULL, null=True, blank=True)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Примененный промокод'
        verbose_name_plural = 'Примененные промокоды'

class TransportCompany(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название организации')

    class Meta:
        verbose_name = 'Транспортная компания'
        verbose_name_plural = 'Транспортные компании'

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, SetPasswordForm
from django.core.exceptions import ValidationError
from .models import CustomUser, Profile


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=False, label='Электронная почта')
    first_name = forms.CharField(required=False, label='Имя')
    last_name = forms.CharField(required=False, label='Фамилия')
    patronymic = forms.CharField(required=False, label='Отчество')
    # phone = forms.CharField(required=False, label='Телефон')
    phone = forms.CharField(label='Телефон', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+7 999 123-45-67'}))

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'patronymic', 'phone', 'password1', 'password2')
        exclude = ('type',)

    def save(self, commit=True):

        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    
    def clean(self):
        phone = self.cleaned_data['phone']
        phone = '+' + ''.join([char for char in phone if char.isdigit()])


class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=False, label='Электронная почта',widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(required=False, label='Имя',widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=False, label='Фамилия',widget=forms.TextInput(attrs={'class': 'form-control'}))
    patronymic = forms.CharField(required=False, label='Отчество',widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(required=False, label='Телефон',widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'patronymic', 'phone', 'photo')
        exclude = ('password',)
    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['photo'].required = False


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


    error_messages = {
        "invalid_login": 
            'НЕВЕРНЫЙ ЛОГИН И/ИЛИ ПАРОЛЬ. Попробуйте снова.'
        ,
        "inactive": "This account is inactive.",
    }
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError(
                "Этот аккаунт не активен.",
                code='inactive',
            )
        if user.ban:
            raise ValidationError(
                "Вы не можете войти, обратитесь к администратору",
                code='fired',
            )

    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'password']


class ProfileRegisterForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class UserUpdateForm(forms.ModelForm):
    password = forms.CharField(label='Новый пароль', widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput, required=False)
    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'patronymic', 'phone', 'photo']
        exclude = ['username', 'sender', 'type']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Пароли не совпадают. Пожалуйста, введите пароли заново.")


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['title', 'city', 'region', 'metro', 'street', 'home_number', 'room_number', 'index', 'info']

    def __init__(self, *args, **kwargs):
        super(AddressForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = True  # Установка title как обязательного поля

    def save(self, commit=True):
        instance = super(AddressForm, self).save(commit=False)
        instance.users = self.initial['user']  # Установка значения user из initial
        if commit:
            instance.save()
        return instance

class AddressEditForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['title', 'city', 'region', 'metro', 'street', 'home_number', 'room_number', 'index', 'info']


class CustomUserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=None,
    )
    new_password2 = forms.CharField(
        label="New password confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        self.fields['new_password1'].help_text = "Введите новый пароль."

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

orders/views.py
from django.shortcuts import render

# Create your views here.

templates/cart/cart_item.html
        {% load static %}{% if request.user.is_authenticated %}


    <div class="cart-item">
      <div class="cart-img">
        <input type="checkbox" id="">
          {% if item.item.image %}
             <img src="{{item.item.image.url}}" alt="">
          {% endif %}

      </div>
      <div class="item-hover">
      <h2>{{ item.item.name }}</h2>
      <div class="del-item">
        <img src="static/img/X.svg" alt="">
      </div>
      <div class="item-count">
        <div class="number" data-step="1" data-min="1" data-max="100">
          <input class="number-text" type="text" name="count" value="1">
          <a href="#" class="number-minus">−</a>
          <a href="#" class="number-plus">+</a>
        </div>
        <div class="summ">
          {{ item.item.seil_price }} ₽ \ шт.
        </div>
      </div>
    </div>
    </div>

        {% else %}

    <div class="cart-item">
      <div class="cart-img">
        <input type="checkbox" id="">
          {% if item.image %}
             <img src="{{item.image.url}}" alt="">
          {% endif %}

      </div>
      <div class="item-hover">
      <h2>{{ item.name }}</h2>
      <div class="del-item">
        <img src="static/img/X.svg" alt="">
      </div>
      <div class="item-count">
        <div class="number" data-step="1" data-min="1" data-max="100">
          <input class="number-text" type="text" name="count" value="1">
          <a href="#" class="number-minus">−</a>
          <a href="#" class="number-plus">+</a>
        </div>
        <div class="summ">
          {{ item.seil_price }} ₽ \ шт.
        </div>
      </div>
    </div>
    </div>
        {% endif %}

templates/cart/order.html
{% extends 'default.html' %}{% load static %}

{% block content %}

      <div class="cart-content">
      <nav>
      <div class="breadcrumbs">
        <a href="/">Главная »</a>
        <a href="/order/">Оформление заказа</a>
      </div>
    </nav>
        <h1 style="margin: 0px 0px 20px 0px">{{ title }}</h1>


        <form action="" style="display: flex;box-shadow: 0 8px 24px 0 rgb(8 9 112 / 9%);border-radius: 20px;padding:0px 0px 60px 0px;">

            <div class="cart-items" style="min-height: 700px;box-shadow: none;">
            <div class="order-list">
             <div class="cart-list">

             <!------
             ТРАСПОРТНЫЕ КОМПАНИИ
             ----->

                 <div class="transport-company">
                    {% for item in transport_companies %}
                        <div class="form_radio_btn">
                        <input id="radio-{{ item.id }}" type="radio" name="radio" value="{{ item.id }}" checked>
                        <label for="radio-{{ item.id }}">{{item.name}}</label>
                    </div>
                    {% endfor %}
{#                     <div class="form_radio_btn">#}
{#                        <input id="radio-1" type="radio" name="radio" value="1" checked>#}
{#                        <label for="radio-1">Доставка курьером по СПБ</label>#}
{#                    </div>#}
{##}
{#                    <div class="form_radio_btn">#}
{#                        <input id="radio-2" type="radio" name="radio" value="2">#}
{#                        <label for="radio-2">Самовывоз СПБ</label>#}
{#                    </div>#}
{##}
{#                    <div class="form_radio_btn">#}
{#                        <input id="radio-3" type="radio" name="radio" value="3">#}
{#                        <label for="radio-3">СДЭК</label>#}
{#                    </div>#}
{##}
{#                    <div class="form_radio_btn">#}
{#                        <input id="radio-4" type="radio" name="radio" value="4">#}
{#                        <label for="radio-4">Почта РФ</label>#}
{#                    </div>#}
{#                                           <div class="form_radio_btn">#}
{#                        <input id="radio-5" type="radio" name="radio" value="5">#}
{#                        <label for="radio-5">Boxberry</label>#}
{#                    </div>#}
{##}
{#                    <div class="form_radio_btn">#}
{#                        <input id="radio-6" type="radio" name="radio" value="6">#}
{#                        <label for="radio-6">Яндекс.Доставка</label>#}
{#                    </div>#}
                   </div>


                   <!-------
                   АДРЕСА
                   -------->

                   <div class="adress-nav">
                          <div class="adress-title">Адрес доставки</div>
                          <div class="new-adress" id="openModalButton" style="padding: 9px 0px 9px 20px;color: #00b44e;background: inherit;" data-toggle="modal" data-target="#addAddressModal">Добавить адрес</div>
                   </div>
                        {% if address %}

                        {% for ad in address %}
                            <div class="adress">
                            <div class="item-adress-title">
                                <div class="address_info">{{ ad.street }} {{ ad.home_number }}, {{ ad.room_number }}</div>

                                <div class="drop-down-address-actions">

                                    <div class="drop-down-address-actions">

                                    </div>
                                    <label class="dropdown">

                                      <div class="dd-button">
                                            <img src="{% static 'img/address.svg' %}" alt="">
                                      </div>

                                      <input type="checkbox" class="dd-input" id="test">

                                      <ul class="dd-menu">
                                        <li><a href="{% url 'edit_myaddress' ad.id %}">Изменить</a></li>
                                        <li><a href="{% url 'delete_address' ad.id %}">Удалить</a></li>
                                      </ul>

                                    </label>
                                </div>
                            </div>
                            </div>
                        {% endfor %}

                        {% else %}
                            <div class="adress">
                              <div class="item-adress-title" style="justify-content: flex-start;">
                              <img src="{% static '/img/warning 1.svg' %}" alt="">Нет адресов
                            </div>
                            </div>

                        {% endif %}



                <!-----
                КОММЕНТАРИЙ
                ----->

                  <div class="comment">
                      <p style="margin: 0px 0px 20px 0px;">Комментарий курьеру </p>
                    <input type="text" style="border: 1px solid #999999;" placeholder="Оставьте комментарий к заказу">
                  </div>


             <!--------
             ПОКУПАТЕЛЬ
             -------->

            <h2>Покупатель</h2>
             <div class="order-user">
             <div class="user-input">
              <p>Фамилия</p>
                <input type="text" name="first_name" maxlength="100" id="id_first_name">
            </div>
                    <div class="user-input">
              <p>Имя</p>
                <input type="text" name="last_name" maxlength="100" id="id_last_name">
            </div>
                    <div class="user-input">
              <p>Отчество</p>
          <input type="text" name="patronymic" maxlength="100" id="id_patronymic">
            </div>
            <div class="user-input">
              <p>E-mail</p>
              <input type="email" name="email" value="root@root.root" maxlength="254" id="id_email">
            </div>
            <div class="user-input">
              <p>Телефон</p>
            <input type="text" name="phone" maxlength="24" id="id_phone">
            </div>
             </div>

                <!------
                ПРОМОКОД
                ----->

                <h2 style="margin: 0px 0px 20px 0px;font-size: 24px;font-weight: 600;">Промокод</h2><div class="promo">

                <input type="text" placeholder="Введите промокод">
                <button style="    width: 100%;
                border-radius: 35px;
                background-color: #00B44E;
                color: #FFFFFF;
                text-align: center;
                border: none;
                padding: 20px 20px 20px 20px;
                font-weight: 700;
                cursor: pointer;border-radius: 0px 15px 15px 0px;max-width: 200px;">ПРИМЕНИТЬ</button>
               </div>



            <!--------
            БОНУСЫ
            ------->

              <div class="bonus-pay">
                <div class="bonus">
                  <input type="checkbox">
                  <label for="">Оплатить бонусами</label>
                </div>
                <p>Доступно {{balance}} бонусов</p>
              </div>


                <button type="submit" class="order-button">ОФОРМИТЬ ЗАКАЗ</button>
        </div>

            
</div>
          </div>



            <div class="cart-info">
                <h2>Ваш заказ</h2>
              <div class="cart-price">
                <div class="count">
                  <span>
                    Товары( {{ total_quantity }} )
                  </span>
                </div>
                <div class="sail">
                  Скидка <span>{{ total_discount }} ₽</span>
                </div>
                  <div class="bonus-total">
                      Бонусы
                  </div>
                <div class="summa">
                  Итого <span>{{ total }} ₽</span>
                </div>
              </div>
            </div>
      </form>

      <script>
document.addEventListener("DOMContentLoaded", function () {
    const cartItems = document.querySelectorAll(".item");

    cartItems.forEach((item) => {
        const quantityInput = item.querySelector(".number-text");
        const quantityMinus = item.querySelector(".number-minus");
        const quantityPlus = item.querySelector(".number-plus");
        const itemID = item.getAttribute("data-item-id");

        quantityMinus.addEventListener("click", function (event) {
            event.preventDefault();
            let quantity = parseInt(quantityInput.getAttribute("data-quantity"));
            if (quantity > 1) {
                quantity--;
                updateCartQuantity(itemID, quantity);
            }
        });

        quantityPlus.addEventListener("click", function (event) {
            event.preventDefault();
            let quantity = parseInt(quantityInput.getAttribute("data-quantity"));
            quantity++;
            updateCartQuantity(itemID, quantity);
        });
    });

    function updateCartQuantity(itemID, newQuantity) {
        fetch(`/update_quantity/${itemID}/${newQuantity}`, { method: 'POST' })
            .then(response => response.json())
            .then(data => {
                // Обновите статистику корзины в реальном времени
                const totalItemsElement = document.querySelector("#total-items");
                const totalPriceElement = document.querySelector("#total-price");
                const totalDiscountElement = document.querySelector("#total-discount");
                const totalWithoutDiscountElement = document.querySelector("#total-without-discount");

                totalItemsElement.textContent = data.total_items;
                totalPriceElement.textContent = data.total_price;
                totalDiscountElement.textContent = data.total_discount;
                totalWithoutDiscountElement.textContent = data.total_without_discount;
            });
    }
});




        // Находим элементы формы
      var selectAllCheckbox = document.getElementById('select-all');
      var checkboxes = document.querySelectorAll('input[type=checkbox]');

      // Привязываем обработчик события "click" к флажку "выбрать все"
      selectAllCheckbox.addEventListener('click', function(event) {
      // Обходим все элементы формы с флажком checkbox
      for(var i = 0; i < checkboxes.length; i++) {
      // Устанавливаем свойство "checked" для всех элементов формы с флажком
      checkboxes[i].checked = selectAllCheckbox.checked;
      }
      });
      </script>
      </div>
    </div>



      <style type="text/css">
.dropdown {
  display: inline-block;
  position: relative;
}

.dd-button {

}

.dd-button:after {

}

.dd-button:hover {
    opacity: 0.9;
    cursor: pointer;
}


.dd-input {
  display: none;
}

.dd-menu {
  position: absolute;
  top: 100%;
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0;
  margin: 2px 0 0 0;
  box-shadow: 0 0 6px 0 rgba(0,0,0,0.1);
  background-color: #ffffff;
  list-style-type: none;
    z-index: 9;
    right: 0%;
}

.dd-input + .dd-menu {
  display: none;
}

.dd-input:checked + .dd-menu {
  display: block;
}

.dd-menu li {
  padding: 10px 20px;
  cursor: pointer;
  white-space: nowrap;
}

.dd-menu li:hover {
  background-color: #f6f6f6;
}

.dd-menu li a {
  display: block;
  margin: -10px -20px;
  padding: 10px 20px;
}

.dd-menu li.divider{
  padding: 0;
  border-bottom: 1px solid #cccccc;
}
          .user-input input{
              border: 2px solid #00B44E;
    border-radius: 25px;
    padding: 20px 20px 20px 20px;
    width: 100%;
    font-size: 20px;
    box-sizing: border-box;
          }
    .number {
	user-select: none;
	position: relative;
	text-align: left;
	padding: 0;
	width: 140px;
	display: inline-block;
  border: none;
  border-radius: 20px;
  margin: 0px 20px 0px 0px;
        background: #edf0f2;
}
.number-minus, .number-plus {
	position: absolute;
	top: 0;
	width: 40px;
	height: 32px;
	line-height: 32px;
	display: block;
	font-size: 20px;
	font-weight: 600;
	text-align: center;
	font-family: arial;
  color: #CCCCCC;
	text-decoration: none;
}
.number-minus {
	left: 0;
}
.number-plus {
	right: 0;
}

.number-text{
	display: inline-block;
	font-size: 14px;
	color: #000;
	line-height: 32px;
	height: 32px;
	padding: 0;
	margin: 0 0 0 42px;
	background: inherit;
	outline: none;
	border: none;
	width: 57px;
	text-align: center;
}
  </style>


{% endblock %}